const indianStates = [
  { english: "Andhra Pradesh", native: "ఆంధ్ర ప్రదేశ్" },
  { english: "Arunachal Pradesh", native: "अरुणाचल प्रदेश" },
  { english: "Assam", native: "অসম" },
  { english: "Bihar", native: "बिहार" },
  { english: "Chhattisgarh", native: "छत्तीसगढ़" },
  { english: "Goa", native: "गोवा" },
  { english: "Gujarat", native: "ગુજરાત" },
  { english: "Haryana", native: "ਹਰਿਆਣਾ" },
  { english: "Himachal Pradesh", native: "हिमाचल प्रदेश" },
  { english: "Jharkhand", native: "झारखण्ड" },
  { english: "Karnataka", native: "ಕರ್ನಾಟಕ" },
  { english: "Kerala", native: "കേരളം" },
  { english: "Madhya Pradesh", native: "मध्य प्रदेश" },
  { english: "Maharashtra", native: "महाराष्ट्र" },
  { english: "Manipur", native: "মণিপুর" },
  { english: "Meghalaya", native: "मेघालय" },
  { english: "Mizoram", native: "মিজোরাম" },
  { english: "Nagaland", native: "नागालैंड" },
  { english: "Odisha", native: "ଓଡ଼ିଶା" },
  { english: "Punjab", native: "ਪੰਜਾਬ" },
  { english: "Rajasthan", native: "राजस्थान" },
  { english: "Sikkim", native: "सिक्किम" },
  { english: "Tamil Nadu", native: "தமிழ்நாடு" },
  { english: "Telangana", native: "తెలంగాణ" },
  { english: "Tripura", native: "ত্রিপুরা" },
  { english: "Uttar Pradesh", native: "उत्तर प्रदेश" },
  { english: "Uttarakhand", native: "उत्तराखण्ड" },
  { english: "West Bengal", native: "পশ্চিমবঙ্গ" },
];

export default indianStates;
